package sumaApp;


/**
* sumaApp/suma.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sumaApp.idl
* miércoles 11 de abril de 2018 09:16:34 PM COT
*/

public interface suma extends sumaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface suma
